
import { SocialLink, ArtPiece, Language } from './types';

export const SOCIAL_LINKS: SocialLink[] = [
  { platform: 'X (Twitter)', url: 'https://x.com/co3spiral', icon: 'custom-x', description: '' },
  { platform: 'Instagram', url: 'https://www.instagram.com/co_3spiral', icon: 'fab fa-instagram', description: '' },
  { platform: 'Zora', url: 'https://zora.co/@3spiral', icon: 'custom-zora', description: '' },
  { platform: 'Objkt', url: 'https://objkt.com/users/tz1hjc5fAb5abh69VadryWi9E3qfT3dEKkHk', icon: 'custom-objkt', description: '' }
];

export const TRANSLATIONS: Record<Language, any> = {
  pt: {
    manifestoTitle: "O QUE SOMOS",
    manifestoText: "3spiral é um coletivo transdisciplinar formado por artistas trans que atuam no audiovisual, performance, fotografia, cultura do skate e experimentação digital. O nome evoca a simultaneidade de passado, presente e futuro, articulada ao número 3 como referência à Web3 e às imaginações de uma diáspora cibernética. Enraizado em memórias afro-brasileiras e indígenas, o coletivo investiga multiplicidades de gênero, política do corpo e tecnologias ancestrais em diálogo com mídias contemporâneas. Sua prática articula ritual, movimento urbano e estética digital para tensionar binarismos coloniais e expandir narrativas sobre existências trans.",
    archiveTitle: "ARQUIVO",
    aboutTitle: "SOBRE NÓS",
    worksTitle: "TRABALHOS",
    networksTitle: "REDES",
    bosqueMainDesc: "Bosque Gracias é um território artístico familiar localizado na zona rural da Patagônia argentina, entre El Hoyo e Epuyén. Há doze anos, uma família de artistas vive e constrói esse espaço, atuando principalmente no audiovisual e em práticas ligadas à Web3. O território promove residências que conectam natureza, tecnologia e criação coletiva.\n\nEm janeiro de 2025, Kaêu e Qab participaram da residência como artistas residentes. No ano seguinte retornaram a convite da equipe, integrando o núcleo de documentação fotográfica e audiovisual. O que inicialmente seria apenas o registro da residência transformou se em um documentário sobre o próprio Bosque Gracias.\n\nDurante o período da residência, o território foi atingido por incêndios devastadores. Das cinco casas que compunham o espaço, apenas uma permaneceu de pé. Equipamentos de audiovisual, arquivos históricos e registros de memória foram perdidos. O trabalho de documentação passou a acompanhar o antes, o durante e o depois do fogo, revelando a vulnerabilidade de territórios autônomos diante do abandono estatal e de políticas ambientais insuficientes.",
    dia1Title: "Título: Dia 1",
    dia1Text: "O primeiro dia foi dedicado ao reconhecimento do território e de sua história. Os participantes da residência foram introduzidos ao percurso da família até a consolidação do Bosque Gracias e conduzidos pelos biomas do espaço.\n\nFoi visitada uma área de mata fechada com árvores que ultrapassam quatrocentos anos. A experiência instaurou um estado de escuta e presença coletiva. Em determinado momento, os participantes passaram a brincar de esconde esconde entre as árvores, ativando o espaço por meio do corpo e do jogo.\n\nO vídeo foi registrado por Kaêu e Qab utilizando GoPro 13 e câmera compacta Kodak. As fotografias foram realizadas com Canon 60D. A edição foi conduzida majoritariamente por Qab, em diálogo colaborativo com Kaêu.",
    dia2Title: "Dia 2",
    tallerTitle: "Taller de Cianotipia",
    dia2Text: "No segundo dia ocorreu o taller de cianotipia, conduzido por Rocío, como parte das atividades oferecidas aos participantes da residência. O encontro iniciou com uma conversa sobre a técnica e apresentação de trabalhos anteriores, seguido pelo processo coletivo de criação.\n\nKaêu assumiu a direção do registro audiovisual, buscando uma câmera que acompanha de perto mãos e gestos e, em outros momentos, observa à distância, como se espreitasse o processo criativo. O foco esteve na relação entre corpo, matéria, luz e tempo.\n\nO vídeo foi gravado com câmera compacta Kodak. A edição foi conduzida por Kaêu, com contribuições de Qab.",
    vegetacaoDesc: "Trabalho criado em colaboração com @qabqabqab e @olhosdesuna, combinando fotos tiradas em Bosque Gracias, colagem digital, arte ASCII e ilustração.",
    sinteseDesc: "A obra nasce das fotografias realizadas por Kaêu e Qab durante o primeiro dia de reconhecimento do território. A partir desses registros, elementos do bosque, como flores, texturas e fragmentos orgânicos, foram isolados e transformados em adesivos digitais.\n\nCom esses fragmentos, Kaêu e Qab criaram uma colagem que tensiona documentação e fabulação. A peça funciona como memória expandida do encontro com o território, misturando registro, jogo e reinvenção visual do bosque.",
    artesTitle: "ARTES",
    kaeuBio: "Kaêu Esuna é multiartista quilombola cuja prática atravessa performance, audiovisual, direção criativa e arte educação. Iniciou no teatro em 2014 na Casa de Cultura Cora Coralina e formou se em Teatro pela Etec de Artes em 2020, onde apresentou o trabalho autoral As coisas que deixei ali. É fundador e diretor do projeto teatral Buraco Negro, estreado em 2024 com fomento do Programa VAI, e foi integrante da CIA DezAfio, atuando em teatro sensorial, teatro de rua e intervenções no centro de São Paulo. Em 2022 assumiu a direção criativa do projeto Quem vê close, não vê corre e atuou na mediação e disposição de obras na exposição Inflamação, de Anish Kapoor, ampliando sua experiência em processos curatoriais.\n\nEm 2025 aprofundou sua atuação no audiovisual ao ser selecionado para o núcleo de Direção de Fotografia do Instituto Criar, onde dirigiu Clamorfia e assinou a direção de fotografia da videoarte YPY. Atuou também na produção de elenco, produção de set e operação de câmera no videocast Vem Aí e realizou o making of do fashion filme A Retomada do Equilíbrio. É cofundador do coletivo 3spiral, núcleo transdisciplinar que investiga Web3, estética trans e memória na diáspora. Sua pesquisa articula gênero, território e ancestralidade a partir de uma perspective afro brasileira e indígena, compreendendo o quilombo como tecnologia histórica de confluência e resistência, mobilizando corpo e imagem como estratégias de reinvenção simbólica e afirmação de corpos dissidente.",
    qabBio: "Artista transdisciplinar de São Paulo, Qab Lima atua nas interseções entre arte digital, escultura, pintura, animação 2D, modelagem 3D, edição de vídeo e produção musical. Sua prática investiga identidade, gênero e questões sociopolíticas, criando obras que transitam entre o físico e o digital, o sensível e o tecnológico, muitas vezes incorporando elementos interativos e referências ancestrais.\n\nCom nove anos de experiência em publicidade como Designer, Motion Designer e UI/UX, desenvolveu forte domínio em comunicação visual, narrativa e estratégias de engajamento. Desde 2021, participa ativamente do ecossistema Web3, explorando blockchain, NFTs e comunidades onchain como extensões de sua pesquisa artística. A partir de 2025, passou também a atuar no desenvolvimento de websites, ampliando sua atuação para a criação de experiências digitais completas.\n\nSeu trabalho é guiado pela colaboração e pela construção coletiva, buscando conectar práticas artísticas, tecnologia e comunidade em projetos que gerem crescimento, impacto cultural e novas possibilidades de imaginação.",
    bosqueShortDesc: "Bosque Gracias é um território artístico familiar na Patagônia Argentina que une natureza, tecnologia e criação coletiva. Após incêndios devastadores em 2026, o projeto d...",
    nostalgiaShortDesc: "Esta coleção transforma memórias em futuro, recriando estéticas digitais da infância — pixels, colagens, brilhos e universos online — a partir de uma perspectiva trans e..."
  },
  en: {
    manifestoTitle: "WHAT WE ARE",
    manifestoText: "3spiral is a transdisciplinary collective formed by trans artists working in audiovisual, performance, photography, skate culture, and digital experimentation. The name evokes the simultaneity of past, present, and future, articulated with the number 3 as a reference to Web3 and the imaginations of a cybernetic diaspora. Rooted in Afro-Brazilian and indigenous memories, the collective investigates gender multiplicities, body politics, and ancestral technologies in dialogue with contemporary media. Their practice articulates ritual, urban movement, and digital aesthetics to challenge colonial binarisms and expand narratives on trans existences.",
    archiveTitle: "ARCHIVE",
    aboutTitle: "ABOUT US",
    worksTitle: "WORKS",
    networksTitle: "NETWORKS",
    bosqueMainDesc: "Bosque Gracias is a family artistic territory located in rural Argentine Patagonia, between El Hoyo and Epuyén. For twelve years, a family of artists has lived and built this space, acting mainly in audiovisual and Web3-related practices. The territory promotes residencies that connect nature, technology, and collective creation.\n\nIn January 2025, Kaêu and Qab participated in the residency as resident artists. The following year they returned at the team's invitation, integrating the photographic and audiovisual documentation core. What was initially meant to be just a record of the residency transformed into a documentary about Bosque Gracias itself.\n\nDuring the residency period, the territory was hit by devastating fires. Of the five houses that made up the space, only one remained standing. Audiovisual equipment, historical archives, and memory records were lost. The documentation work followed the before, during, and after the fire, revealing the vulnerability of autonomous territories in the face of state neglect and insufficient environmental policies.",
    dia1Title: "Title: Day 1",
    dia1Text: "The first day was dedicated to recognizing the territory and its history. The residency participants were introduced to the family's journey to the consolidation of Bosque Gracias and guided through the area's biomes.\n\nA dense forest area with trees over four hundred years old was visited. The experience established a state of collective listening and presence. At a certain point, the participants began to play hide-and-seek among the trees, activating the space through the body and play.\n\nThe video was recorded by Kaêu and Qab using a GoPro 13 and a compact Kodak camera. The photographs were taken with a Canon 60D. The editing was mainly conducted by Qab, in a collaborative dialogue with Kaêu.",
    dia2Title: "Day 2",
    tallerTitle: "Cyanotype Workshop",
    dia2Text: "On the second day, the cyanotype workshop occurred, led by Rocío, as part of the activities offered to the residency participants. The meeting started with a conversation about the technique and presentation of previous works, followed by the collective creation process.\n\nKaêu took over the direction of the audiovisual record, seeking a camera that closely follows hands and gestures and, at other times, observes from a distance, as if peering into the creative process. The focus was on the relationship between body, matter, light, and time.\n\nThe video was recorded with a compact Kodak camera. The editing was led by Kaêu, with contributions from Qab.",
    vegetacaoDesc: "Work created in collaboration with @qabqabqab and @olhosdesuna, combining photos taken in Bosque Gracias, digital collage, ASCII art, and illustration.",
    sinteseDesc: "The piece is born from the photographs taken by Kaêu and Qab during the first day of territory recognition. From these records, elements of the forest, such as flowers, textures, and organic fragments, were isolated and transformed into digital stickers.\n\nWith these fragments, Kaêu and Qab created a collage that tensions documentation and fabulation. The piece works as an expanded memory of the encounter with the territory, mixing record, play, and visual reinvention of the forest.",
    artesTitle: "ARTS",
    kaeuBio: "Kaêu Esuna is a quilombola multi-artist whose practice spans performance, audiovisual, creative direction, and art education. They began in theater in 2014 at the Casa de Cultura Cora Coralina and graduated in Theater from Etec de Artes in 2020, where they presented the original work 'As coisas que deixei ali'. They are the founder and director of the theatrical project Buraco Negro, debuted in 2024 with funding from the VAI Program, and were a member of CIA DezAfio, acting in sensory theater, street theater, and interventions in the center of São Paulo. In 2022, they assumed the creative direction of the project 'Quem vê close, não vê corre' and acted in the mediation and arrangement of works in the exhibition Inflamação, by Anish Kapoor, expanding their experience in curatorial processes.\n\nIn 2025, they deepened their work in audiovisual by being selected for the Cinematography core of the Instituto Criar, where they directed Clamorfia and signed the cinematography of the video art YPY. They also worked in casting production, set production, and camera operation in the videocast Vem Aí and directed the making-of of the fashion film A Retomada do Equilíbrio. They are a co-founder of the 3spiral collective, a transdisciplinary core that investigates Web3, trans aesthetics, and memory in the diaspora. Their research articulates gender, territory, and ancestry from an Afro-Brazilian and indigenous perspective, understanding the quilombo as a historical technology of confluence and resistance, mobilizing body and image as strategies for symbolic reinvention and affirmation of dissident bodies.",
    qabBio: "A transdisciplinary artist from São Paulo, Qab Lima works at the intersections of digital art, sculpture, painting, 2D animation, 3D modeling, video editing, and music production. His practice investigates identity, gender, and sociopolitical issues, creating works that transition between the physical and digital, the sensitive and the technological, often incorporating interactive elements and ancestral references.\n\nWith nine years of experience in advertising as a Designer, Motion Designer, and UI/UX, he developed a strong mastery of visual communication, narrative, and engagement strategies. Since 2021, he has been an active participant in the Web3 ecosystem, exploring blockchain, NFTs, and onchain communities as extensions of his artistic research. Starting in 2025, he also began working on website development, expanding his work to the creation of complete digital experiences.\n\nHis work is guided by collaboration and collective construction, seeking to connect artistic practices, technology, and community in projects that generate growth, cultural impact, and new possibilities of imagination.",
    bosqueShortDesc: "Bosque Gracias is a family artistic territory in Argentine Patagonia that unites nature, technology, and collective creation. After devastating fires in 2026, the d...",
    nostalgiaShortDesc: "This collection transforms memories into the future, recreating digital aesthetics from childhood — pixels, collages, sparkles, and online universes — from a trans and..."
  },
  es: {
    manifestoTitle: "QUÉ SOMOS",
    manifestoText: "3spiral es un colectivo transdisciplinario formado por artistas trans que trabajan en audiovisual, performance, fotografía, cultura skate y experimentación digital. El nombre evoca la simultaneidad de pasado, presente y futuro, articulada con el número 3 como referencia a la Web3 y a las imaginaciones de una diáspora cibernética. Arraigado en memorias afrobrasileñas e indígenas, el colectivo investiga multiplicidades de género, política del cuerpo y tecnologías ancestrales en diálogo con medios contemporáneos. Su práctica articula ritual, movimiento urbano y estética digital para tensionar los binarismos coloniales y ampliar las narrativas sobre las existencias trans.",
    archiveTitle: "ARCHIVO",
    aboutTitle: "SOBRE NOSOTROS",
    worksTitle: "TRABAJOS",
    networksTitle: "REDES",
    bosqueMainDesc: "Bosque Gracias es un territorio artístico familiar ubicado en la zona rural de la Patagonia argentina, entre El Hoyo y Epuyén. Durante doce años, una familia de artistas ha vivido y construido este espacio, trabajando principalmente en audiovisuales y prácticas vinculadas a la Web3. El territorio promueve residencias que conectan naturaleza, tecnología y creación colectiva.\n\nEn enero de 2025, Kaêu y Qab participaron en la residencia como artistas residentes. Al año siguiente regresaron por invitación del equipo, integrándose al núcleo de documentación fotográfica y audiovisual. Lo que inicialmente sería sólo el registro de la residencia se transformó en un documental sobre el propio Bosque Gracias.\n\nDurante el período de la residencia, el territorio se vio afectado por incendios devastadores. De las cinco casas que compunham el espacio, sólo una quedó en pie. Se perdieron equipos audiovisuales, archivos históricos y registros de memoria. El trabajo de documentación pasó a acompañar el antes, el durante y el después del fuego, revelando la vulnerabilidad de territorios autónomos ante el abandono estatal y políticas ambientales insuficientes.",
    dia1Title: "Título: Día 1",
    dia1Text: "El primer día estuvo dedicado al reconocimiento del territorio y su historia. Los participantes de la residencia conocieron el recorrido de la familia hasta la consolidación de Bosque Gracias y fueron guiados por los biomas del espacio.\n\nSe visitó un área de bosque cerrado con árboles de más de cuatrocientos años. La experiencia estableció un estado de escucha y presencia colectiva. En cierto momento, los participantes comenzaron a jugar a las escondidas entre los árboles, activando el espacio a través del cuerpo y el juego.\n\nEl video fue grabado por Kaêu y Qab utilizando una GoPro 13 y una cámara Kodak compacta. Las fotografías fueron tomadas con una Canon 60D. El montaje fue realizado mayoritariamente por Qab, en diálogo colaborativo con Kaêu.",
    dia2Title: "Día 2",
    tallerTitle: "Taller de Cianotipia",
    dia2Text: "En el segundo día se realizó el taller de cianotipia, dirigido por Rocío, como parte de las actividades ofrecidas a los participantes de la residencia. El encuentro se inició con una charla sobre la técnica y presentación de trabajos anteriores, seguido del proceso de creación colectiva.\n\nKaêu asumió la dirección del registro audiovisual, buscando una cámara que siga de cerca manos y gestos y, en otros momentos, observe desde la distancia, como acechando el proceso creativo. El foco estuvo en la relación entre cuerpo, materia, luz y tiempo.\n\nEl vídeo fue grabado con una cámara compacta Kodak. La edición estuvo a cargo de Kaêu, con aportes de Qab.",
    vegetacaoDesc: "Obra creada en colaboración con @qabqabqab y @olhosdesuna, combinando fotos tomadas en Bosque Gracias, collage digital, arte ASCII e ilustración.",
    sinteseDesc: "La obra nace de las fotografías tomadas por Kaêu y Qab durante el primer día de reconocimiento del territorio. A partir de estos registros, se aislaron elementos del bosque, como flores, texturas y fragmentos orgánicos, y se transformaron en pegatinas digitales.\n\nCon estos fragmentos, Kaêu y Qab criaron un collage que tensiona documentación y fabulación. La pieza funciona como una memoria expandida del encuentro con el territorio, mezclando registro, juego y reinvención visual del bosque.",
    artesTitle: "ARTES",
    kaeuBio: "Kaêu Esuna es un multiartista quilombola cuya práctica abarca performance, audiovisual, dirección creativa y educación artística. Se inició en el teatro en 2014 en la Casa de Cultura Cora Coralina y se graduó en Teatro en la Etec de Artes en 2020, donde presentó la obra original 'As coisas que deixei ali'. Es fundador y director del proyecto teatral Buraco Negro, estrenado en 2024 con financiamiento del Programa VAI, y fue integrante de la CIA DezAfio, actuando en teatro sensorial, teatro de calle e intervenciones en el centro de São Paulo. En 2022 asumió la dirección creativa del proyecto 'Quem vê close, não vê corre' y actuó en la mediación y disposición de obras en la exposición Inflamação, de Anish Kapoor, ampliando su experiencia en procesos curatoriales.\n\nEn 2025 profundizó su actuación en el audiovisual al ser seleccionado para el núcleo de Dirección de Fotografía del Instituto Criar, donde dirigió Clamorfia y firmó la dirección de fotografía de la videoarte YPY. Actuó también en la producción de elenco, producción de set y operación de cámara en el videocast Vem Aí e realizó el making of del fashion filme A Retomada do Equilíbrio. Es cofundador del colectivo 3spiral, núcleo transdisciplinario que investiga Web3, estética trans y memoria en la diáspora. Su investigación articula género, territorio y ancestralidad desde una perspectiva afrobrasileña e indígena, comprendiendo el quilombo como tecnología histórica de confluencia y resistencia, movilizando cuerpo e imagen como estrategias de reinvención simbólica y afirmación de cuerpos disidentes.",
    qabBio: "Artista transdisciplinario de São Paulo, Qab Lima trabaja en las intersecciones entre arte digital, escultura, pintura, animación 2D, modelado 3D, edición de video y producción musical. Su práctica investiga identidad, género y cuestiones sociopolíticas, creando obras que transitam entre lo físico y lo digital, lo sensible y lo tecnológico, a menudo incorporando elementos interactivos y referencias ancestrales.\n\nCon nueve años de experiencia en publicidad como Diseñador, Motion Designer y UI/UX, desarrolló un fuerte dominio en comunicación visual, narrativa y estrategias de compromiso. Desde 2021, participa activamente en el ecosistema Web3, explorando blockchain, NFTs y comunidades onchain como extensiones de su investigación artística. A partir de 2025, pasó también a trabalhar no desenvolvimento de sites web, ampliando sua atuação para a criação de experiências digitais completas.\n\nSu trabalho se guia por la colaboração e pela construção coletiva, buscando conectar práticas artísticas, tecnologia e comunidade em projetos que gerem crescimento, impacto cultural e novas possibilidades de imaginação.",
    bosqueShortDesc: "Bosque Gracias es un territorio artístico familiar en la Patagonia Argentina que une naturaleza, tecnología y creación colectiva. Tras incendios devastadores en 2026, el pr...",
    nostalgiaShortDesc: "Esta colección transforma memorias en futuro, recreando estéticas digitales de la infancia — píxeles, collages, brillos y universos online — desde una perspectiva trans y..."
  }
};

export const GALLERY: ArtPiece[] = [
  { 
    id: '1', 
    title: 'Bosque Gracias Summer 2026', 
    imageUrl: 'https://lavender-worrying-clam-733.mypinata.cloud/ipfs/bafybeie5dbiugaytr5jvc45yhnmaeso36tr4oado7rdzvxtq4vshox4pwy', 
    description: 'Bosque Gracias é um território artístico familiar na Patagônia Argentina que une natureza, tecnologia e criação coletiva. Após incêndios devastadores em 2026, o projeto d...'
  },
  { 
    id: '2', 
    title: 'Nostalgia Utópica', 
    imageUrl: 'https://lavender-worrying-clam-733.mypinata.cloud/ipfs/bafybeihgzpmuyaxrolt37rvsv6usqcovfrqgqpcylswqghd7rfbxuisdve', 
    description: 'Esta coleção transforma memórias em futuro, recriando estéticas digitais da infância — pixels, colagens, brilhos e universos online — a partir de uma perspectiva trans e...'
  }
];
