
import { SocialLink, ArtPiece, Language } from './types';

export const SOCIAL_LINKS: SocialLink[] = [
  { platform: 'X (Twitter)', url: 'https://x.com/co3spiral', icon: 'custom-x', description: '' },
  { platform: 'Instagram', url: 'https://www.instagram.com/co_3spiral', icon: 'fab fa-instagram', description: '' },
  { platform: 'Zora', url: 'https://zora.co/@3spiral', icon: 'custom-zora', description: '' },
  { platform: 'Objkt', url: 'https://objkt.com/users/tz1hjc5fAb5abh69VadryWi9E3qfT3dEKkHk', icon: 'custom-objkt', description: '' }
];

export const TRANSLATIONS: Record<Language, any> = {
  pt: {
    manifestoTitle: "O QUE SOMOS",
    manifestoText: "3spiral é um coletivo transdisciplinar formado por artistas trans que atuam no audiovisual, performance, fotografia, cultura do skate e experimentação digital. O nome evoca a simultaneidade de passado, presente e futuro, articulada ao número 3 como referência à Web3 e às imaginações de uma diáspora cibernética. Enraizado em memórias afro-brasileiras e indígenas, o coletivo investiga multiplicidades de gênero, política do corpo e tecnologias ancestrais em diálogo com mídias contemporâneas. Sua prática articula ritual, movimento urbano e estética digital para tensionar binarismos coloniais e expandir narrativas sobre existências trans.",
    archiveTitle: "ARQUIVO",
    aboutTitle: "SOBRE NÓS",
    worksTitle: "TRABALHOS",
    networksTitle: "REDES",
    bosqueMainDesc: "Bosque Gracias é um território artístico familiar localizado na zona rural da Patagônia argentina, entre El Hoyo e Epuyén. Há doze anos, uma família de artistas vive e constrói esse espaço, atuando principalmente no audiovisual e em práticas ligadas à Web3. O território promove residências que conectam natureza, tecnologia e criação coletiva.\n\nEm janeiro de 2025, Kaêu e Qab participaram da residência como artistas residentes. No ano seguinte retornaram a convite da equipe, integrando o núcleo de documentação fotográfica e audiovisual. O que inicialmente seria apenas o registro da residência transformou se em um documentário sobre o próprio Bosque Gracias.\n\nDurante o período da residência, o território foi atingido por incêndios devastadores. Das cinco casas que compunham o espaço, apenas uma permaneceu de pé. Equipamentos de audiovisual, arquivos históricos e registros de memória foram perdidos. O trabalho de documentação passou a acompanhar o antes, o durante e o depois do fogo, revelando a vulnerabilidade de territórios autônomos diante do abandono estatal e de políticas ambientais insuficientes.",
    dia1Title: "Dia 1",
    dia1Text: "O primeiro dia foi dedicado ao reconhecimento do território e de sua história. Os participantes da residência foram introduzidos ao percurso da família até a consolidação do Bosque Gracias e conduzidos pelos biomas do espaço.\n\nFoi visitada uma área de mata fechada com árvores que ultrapassam quatrocentos anos. A experiência instaurou um estado de escuta e presença coletiva. Em determinado momento, os participantes passaram a brincar de esconde esconde entre as árvores, ativando o espaço por meio do corpo e do jogo.\n\nO vídeo foi registrado por Kaêu e Qab utilizando GoPro 13 e câmera compacta Kodak. As fotografias foram realizadas com Canon 60D. A edição foi conduzida majoritariamente por Qab, em diálogo colaborativo com Kaêu.",
    dia2Title: "Dia 2",
    tallerTitle: "Taller de Cianotipia",
    dia2Text: "No segundo dia ocorreu o taller de cianotipia, conduzido por Rocío, como parte das atividades oferecidas aos participantes da residência. O encontro iniciou com uma conversa sobre a técnica e apresentação de trabalhos anteriores, seguido pelo processo coletivo de criação.\n\nKaêu assumiu a direção do registro audiovisual, buscando uma câmera que acompanha de perto mãos e gestos e, em outros momentos, observa à distância, como se espreitasse o processo criativo. O foco esteve na relação entre corpo, matéria, luz e tempo.\n\nO vídeo foi gravado com câmera compacta Kodak. A edição foi conduzida por Kaêu, com contribuições de Qab.",
    vegetacaoDesc: "Trabalho criado em colaboração com @qabqabqab e @olhosdesuna, combinando fotos tiradas em Bosque Gracias, colagem digital, arte ASCII e ilustração.",
    sinteseDesc: "A obra nasce das fotografias realizadas por Kaêu e Qab durante o primeiro dia de reconhecimento do território. A partir desses registros, elementos do bosque, como flores, texturas e fragmentos orgânicos, foram isolados e transformados em adesivos digitais.\n\nCom esses fragmentos, Kaêu e Qab criaram uma colagem que tensiona documentação e fabulação. A peça funciona como memória expandida do encontro com o território, misturando registro, jogo e reinvenção visual do bosque.",
    artesTitle: "ARTES",
    kaeuBio: "Kaêu Esuna é multiartista quilombola cuja prática atravessa performance, audiovisual, direção criativa e arte educação. Iniciou no teatro em 2014 na Casa de Cultura Cora Coralina e formou se em Teatro pela Etec de Artes em 2020, onde apresentou o trabalho autoral As coisas que deixei ali. É fundador e diretor do projeto teatral Buraco Negro, estreado em 2024 com fomento do Programa VAI, e foi integrante da CIA DezAfio, atuando em teatro sensorial, teatro de rua e intervenções no centro de São Paulo. Em 2022 assumiu a direção criativa do projeto Quem vê close, não vê corre e atuou na mediação e disposição de obras na exposição Inflamação, de Anish Kapoor, ampliando sua experiência em processos curatoriais.\n\nEm 2025 aprofundou sua atuação no audiovisual ao ser selecionado para o núcleo de Direção de Fotografia do Instituto Criar, onde dirigiu Clamorfia e assinou a direção de fotografia da videoarte YPY. Atuou também na produção de elenco, produção de set e operação de câmera no videocast Vem Aí e realizou o making of do fashion filme A Retomada do Equilíbrio. É cofundador do coletivo 3spiral, núcleo transdisciplinar que investiga Web3, estética trans e memória na diáspora. Sua pesquisa articula gênero, território e ancestralidade a partir de uma perspective afro brasileira e indígena, compreendendo o quilombo como tecnologia histórica de confluência e resistência, mobilizando corpo e imagem como estratégias de reinvinção simbólica e afirmação de corpos dissidente.",
    qabBio: "Artista transdisciplinar de São Paulo, Qab Lima atua nas interseções entre arte digital, escultura, pintura, animação 2D, modelagem 3D, edição de vídeo e produção musical. Sua prática investiga identidade, gênero e questões sociopolíticas, criando obras que transitam entre o físico e o digital, o sensível e o tecnológico, muitas vezes incorporando elementos interativos e referências ancestrais.\n\nCom nove anos de experiência em publicidade como Designer, Motion Designer e UI/UX, desenvolveu forte domínio em comunicação visual, narrativa e estratégias de engajamento. Desde 2021, participa ativamente do ecossistema Web3, explorando blockchain, NFTs e comunidades onchain como extensões de sua pesquisa artística. A partir de 2025, passou também a atuar no desenvolvimento de websites, ampliando sua atuação para a criação de experiências digitais completas.\n\nSeu trabalho é guiado pela colaboração e pela construção coletiva, buscando conectar práticas artísticas, tecnologia e comunidade em projetos que gerem crescimento, impacto cultural e novas possibilidades de imaginação.",
    bosqueShortDesc: "Bosque Gracias é um território artístico familiar na Patagônia Argentina que une natureza, tecnologia e criação coletiva. Após incêndios devastadores em 2026, o projeto d...",
    nostalgiaShortDesc: "Esta coleção transforma memórias em futuro, recriando estéticas digitais da infância — pixels, colagens, brilhos e universos online — a partir de uma perspectiva trans e...",
    nostalgiaFullDesc: "Esta coleção nasceu do desejo de transformar nossas memórias em futuro. Ela se inspira nas referências visuais que moldaram nossa infância e adolescência – a arte digital inicial, brilhos, colagens, pixels, universos online – e as recria através de quem somos hoje.\n\nPessoas trans e da diáspora imaginam como aquele tempo poderia ter sido se corpos como os nossos tivessem sido referências. Se nossas existências tivessem ocupado o centro da mídia. Esta coleção é um gesto de reescrever o passado para expandir o que é possível.\n\nAtravés de um processo colaborativo, Kaêu e Qab (@olhosdesuna, @qabqabqab) criaram pacotes de figurinhas originais. A partir desses pacotes, desenvolvemos fundos, construímos colagens digitais e experimentamos com camadas visuais que misturam estética retrô, arte contemporânea e elementos ASCII. Cada peça brinca com fragmentos de memórias que carregamos tanto em nossas mentes quanto remixadas digitalmente com as referências, corpos e afetos que nos inspiram hoje.\n\n“Nostalgia Utópica” trata da recriação de memórias como uma forma de cura e imaginação. Trata-se de brincar de \"Era uma vez\", aproximando quem somos hoje da nossa versão infantil. Trata-se de transformar o anseio em possibilidade.",
    watchHere: "ASSISTA AQUI",
    checkHere: "CONFIRA AQUI",
    clownmorfiaDesc: "Clownmorfia é um fashion film de terror dirigido por Kaêu como Projeto Experimental de Conclusão de Curso no Instituto Criar, sendo uma das dez propostas selecionadas. A obra articula estética de moda e linguagem do horror para tensionar conservadorismo, expressão de gênero e construção social do medo.\n\nO projeto une narrativas ancestrais da oralidade brasileira, presentes em comunidades rurais e ribeirinhas, ao terror slasher contemporâneo. Se no slasher tradicional corpos dissidentes são os primeiros a morrer e a Final Girl sobrevive por se aproximar de um ideal conservador, Clownmorfia inverte essa lógica.\n\nA narrativa acompanha uma família conservadora cuja filha começa a sonhar com palhaços. Esses palhaços simbolizam corpos que rompem com a heteronormatividade e o higienismo estético. O medo não nasce de sua violência, mas do confronto com desejos reprimidos. Ao transformar se em palhaça, a protagonista descobre que o verdadeiro terror está na repressão. O que era visto como ameaça revela se espaço de afeto, coletividade e liberdade.",
    uvs2Desc: "Como parte de uma geração que cresceu durante a transição do mundo analógico para a internet, vivenciando um fluxo avassalador de informações, identidades emergentes e novas formas de expressão, desde as primeiras estéticas digitais até memes e símbolos que carregam múltiplos significados, a coleção revisita minhas referências da adolescência para expressar como vejo o mundo hoje, mesclando-as com minhas referências atuais, processos de documentação, memória e a construção da autoestima para corpos e identidades não binárias, bem como para as identidades originais e ancestrais daquela época.\n\nAo utilizar essas linguagens digitais, a obra propõe uma estratégia de registro histórico e contemplação da ancestralidade – uma ancestralidade que meu povo continua a sustentar e construir ativamente.",
    daguasDesc: "De Antibiko, Kaêu Esuna, Lele Camille, Mareua Sirè, Myka Santos, Nero Santos, Thainá Franklim, Ruby Máximo, 🇧🇷 Brasil\n\nSinopse: D’Águas é um filme experimental gravado em Super 8 que acompanha a travessia silenciosa de uma figura ancestral por lugares no centro de São Paulo. D’Águas, personagem-título, emerge como uma entidade mítica e contemporânea, atravessando espaços onde antes corriam rios e agora soterrados pela cidade. Sem falas, mas guiado por uma trilha sonora original, o filme evoca memórias apagadas, forças ancestrais e uma resistência silenciosa que brota das profundezas da terra e da água.\n\nFicha Técnica:\nInterpretação: Mareua Sirè como D’Águas\nTrilha sonora original: Qab Lima\nConcepção, Roteiro, Produção, Figurino, Performance, Fotografia e Montagem: Trabalho coletivo entre todos os realizadores.",
    brDesc: "Durante a residência artística Bosque Gracias Summer 26' na Patagônia, Argentina, Qab desenvolveu uma coleção baseada em 30 pedras coletadas no rio. Em cada uma Qab desenhou rostos e expressões, permitindo que os ângulos, formas e texturas naturais das pedras orientassem o surgimento de cada personagem. O processo estava profundamente ligado ao tempo passado no rio – observar, tocar e escolher as rochas enquanto a água corria era parte essencial do trabalho. A coleção surge desse encontro entre corpo, paisagem e gesto, explorando a relação de Qab com o desenho, as expressões faciais e a materialidade encontrada no Bosque.",
    bhhDesc: "Durante a residência artística da Kismet Casa em Buenos Aires - Argentina, 2025, Qab desenvolveu uma coleção inspirada nas cabeças das pessoas participantes desta residência. No ambiente web3, é comum ter coleções de designs de cabeças, então Qab decidiu aplicar essa tendência dentro de seu próprio estilo, desenvolvendo um app para a coleção junto com Matt Lee.",
    pinturasDesc: "Diferentes pinturas desenvolvidas em telas, tecidos pintadas com gouache, tinta óleo, giz e outros materiais. Essas obras refletem uma intimidade de sentimentos de Qab, enaltecendo a cultura e beleza preta e indígena."
  },
  en: {
    manifestoTitle: "WHAT WE ARE",
    manifestoText: "3spiral is a transdisciplinary collective formed by trans artists working in audiovisual, performance, photography, skate culture, and digital experimentation. The name evokes the simultaneity of past, present, and future, articulated with the number 3 as a reference to Web3 and the imaginations of a cybernetic diaspora. Rooted in Afro-Brazilian and indigenous memories, the collective investigates gender multiplicities, body politics, and ancestral technologies in dialogue with contemporary media. Their practice articulates ritual, urban movement, and digital aesthetics to challenge colonial binarisms and expand narratives on trans existences.",
    archiveTitle: "ARCHIVE",
    aboutTitle: "ABOUT US",
    worksTitle: "WORKS",
    networksTitle: "NETWORKS",
    bosqueMainDesc: "Bosque Gracias is a family artistic territory located in rural Argentine Patagonia, between El Hoyo and Epuyén. For twelve years, a family of artists has lived and built this space, acting mainly in audiovisual and Web3-related practices. The territory promotes residencies that connect nature, technology, and collective creation.\n\nIn January 2025, Kaêu and Qab participated in the residency as resident artists. The following year they returned at the team's invitation, integrating the photographic and audiovisual documentation core. What was initially meant to be just a record of the residency transformed into a documentary about Bosque Gracias itself.\n\nDuring the residency period, the territory was hit by devastating fires. Of the five houses that made up the space, only one remained standing. Audiovisual equipment, historical archives, and memory records were lost. The documentation work followed the before, during, and after the fire, revealing the vulnerability of autonomous territories in the face of state neglect and insufficient environmental policies.",
    dia1Title: "Day 1",
    dia1Text: "The first day was dedicated to recognizing the territory and its history. The residency participants were introduced to the family's journey to the consolidation of Bosque Gracias and guided through the area's biomes.\n\nA dense forest area with trees over four hundred years old was visited. The experience established a state of collective listening and presence. At a certain point, the participants began to play hide-and-seek among the trees, activating the space through the body and play.\n\nThe video was recorded by Kaêu and Qab using a GoPro 13 and a compact Kodak camera. The photographs were taken with a Canon 60D. The editing was mainly conducted by Qab, in a collaborative dialogue with Kaêu.",
    dia2Title: "Day 2",
    tallerTitle: "Cyanotype Workshop",
    dia2Text: "On the second day, the cyanotype workshop occurred, led by Rocío, as part of the activities offered to the residency participants. The meeting started with a conversation about the technique and presentation of previous works, followed by the collective creation process.\n\nKaêu took over the direction of the audiovisual record, seeking a camera that closely follows hands and gestures and, at other times, observes from a distance, as if peering into the creative process. The focus was on the relationship between body, matter, light, and time.\n\nThe video was recorded with a compact Kodak camera. The editing was led by Kaêu, with contributions from Qab.",
    vegetacaoDesc: "Work created in collaboration with @qabqabqab and @olhosdesuna, combining photos taken in Bosque Gracias, digital collage, ASCII art, and illustration.",
    sinteseDesc: "The piece is born from the photographs taken by Kaêu and Qab during the first day of territory recognition. From these records, elements of the forest, such as flowers, textures, and organic fragments, were isolated and transformed into digital stickers.\n\nWith these fragments, Kaêu and Qab created a collage that tensions documentation and fabulation. The piece works as an expanded memory of the encounter with the territory, mixing record, play, and visual reinvention of the forest.",
    artesTitle: "ARTS",
    kaeuBio: "Kaêu Esuna is a quilombola multi-artist whose practice spans performance, audiovisual, creative direction, and art education. They began in theater in 2014 at the Casa de Cultura Cora Coralina and graduated in Theater from Etec de Artes in 2020, where they presented the original work 'As coisas que deixei ali'. They are the founder and director of the theatrical project Buraco Negro, debuted in 2024 with funding from the VAI Program, and were a member of CIA DezAfio, acting in sensory theater, street theater, and interventions in the center of São Paulo. In 2022, they assumed the creative direction of the project 'Quem vê close, não vê corre' and acted in the mediation and arrangement of works in the exhibition Inflamação, by Anish Kapoor, expanding their experience in curatorial processes.\n\nIn 2025, they deepened their work in audiovisual by being selected for the Cinematography core of the Instituto Criar, where they directed Clamorfia and signed the cinematography of the video art YPY. They also worked in casting production, set production, and camera operation in the videocast Vem Aí and directed the making-of of the fashion film A Retomada do Equilíbrio. They are a co-founder of the 3spiral collective, a transdisciplinary core that investigates Web3, trans aesthetics, and memory in the diaspora. Their research articulates gender, territory, and ancestry from an Afro-Brazilian and indigenous perspective, understanding the quilombo as a historical technology of confluence and resistance, mobilizing body and image as strategies for symbolic reinvention and affirmation of dissident bodies.",
    qabBio: "A transdisciplinary artist from São Paulo, Qab Lima works at the intersections of digital art, sculpture, painting, 2D animation, 3D modeling, video editing, and music production. His practice investigates identity, gender, and sociopolitical issues, creating works that transition between the physical and digital, the sensitive and the technological, often incorporating interactive elements and ancestral references.\n\nWith nine years of experience in advertising as a Designer, Motion Designer, and UI/UX, he developed a strong mastery of visual communication, narrative, and engagement strategies. Since 2021, he has been an active participant in the Web3 ecosystem, exploring blockchain, NFTs, and onchain communities as extensions of his artistic research. Starting in 2025, he also began working on website development, expanding his work to the creation of complete digital experiences.\n\nHis work is guided by collaboration and collective construction, seeking to connect artistic practices, technology, and community in projects that generate growth, cultural impact, and new possibilities of imagination.",
    bosqueShortDesc: "Bosque Gracias is a family artistic territory in Argentine Patagonia that unites nature, technology, and collective creation. After devastating fires in 2026, the d...",
    nostalgiaShortDesc: "This collection transforms memories into the future, recreating digital aesthetics from childhood — pixels, colagens, sparkles, and online universes — from a trans and...",
    nostalgiaFullDesc: "This collection was born from the desire to transform our memories into the future. It draws inspiration from the visual references that shaped our childhood and adolescence – early digital art, sparkles, collages, pixels, online universes – and recreates them through who we are today.\n\nTrans and diaspora people imagine how that time could have been if bodies like ours had been references. If our existences had occupied the media center. This collection is a gesture of rewriting the past to expand what is possible.\n\nThrough a collaborative process, Kaêu and Qab (@olhosdesuna, @qabqabqab) created original sticker packs. From these packs, we developed backgrounds, built digital collages, and experimented with visual layers that mix retro aesthetics, contemporary art, and ASCII elements. Each piece plays with fragments of memories that we carry both in our minds and digitally remixed with the references, bodies, and affections that inspire us today.\n\n“Utopian Nostalgia” is about recreating memories as a form of healing and imagination. It's about playing \"Once Upon a Time,\" bringing who we are today closer to our childhood version. It's about transforming yearning into possibility.",
    watchHere: "WATCH HERE",
    checkHere: "CHECK HERE",
    clownmorfiaDesc: "Clownmorfia is a fashion horror film directed by Kaêu as an Experimental Graduation Project at Instituto Criar. The work articulates fashion aesthetics and horror language to challenge conservatism, gender expression, and the social construction of fear.\n\nThe project joins ancestral narratives from Brazilian orality to contemporary slasher horror. Clownmorfia inverts the traditional logic where dissident bodies are the first to die, revealing fear as a path to collective freedom.",
    uvs2Desc: "The collection revisits adolescent references to express how the world is seen today, merging them with current references, documentation processes, and memory. It proposes a strategy of historical record and ancestral contemplation.",
    daguasDesc: "Experimental film shot in Super 8 following an ancestral figure through São Paulo. D’Águas emerges as a mythical entity crossing spaces where rivers once flowed, evoking erased memories.",
    brDesc: "During the Bosque Gracias Summer 26' artistic residency in Patagonia, Argentina, Qab developed a collection based on 30 stones collected in the river. In each one, Qab drew faces and expressions, allowing the natural angles, shapes, and textures of the stones to guide the emergence of each character. The process was deeply linked to the time spent in the river – observing, touching, and choosing the rocks while the water flowed was an essential part of the work.",
    bhhDesc: "During Kismet Casa's artistic residency in Buenos Aires - Argentina, 2025, Qab developed a collection inspired by the heads of the people participating in this residency. In the web3 environment, it is common to have collections of head designs, so Qab decided to apply this trend within her own style, developing an app for the collection together with Matt Lee.",
    pinturasDesc: "Different paintings developed on canvases and fabrics painted with gouache, oil paint, chalk, and other materials. These works reflect an intimacy of Qab's feelings, praising Black and indigenous culture and beauty."
  },
  es: {
    manifestoTitle: "QUÉ SOMOS",
    manifestoText: "3spiral es un colectivo transdisciplinario formado por artistas trans que trabajan en audiovisual, performance, fotografía, cultura skate y experimentación digital. El nombre evoca la simultaneidad de pasado, presente y futuro, articulada con el número 3 como referencia a la Web3 y a las imaginaciones de una diáspora cibernética. Arraigado en memorias afrobrasileñas e indígenas, el colectivo investiga multiplicidades de género, política del cuerpo y tecnologías ancestrales en diálogo con medios contemporáneos. Su prática articula ritual, movimiento urbano e estética digital para tensionar los binarismos coloniales y ampliar las narrativas sobre las existencias trans.",
    archiveTitle: "ARCHIVO",
    aboutTitle: "SOBRE NOSOTROS",
    worksTitle: "TRABAJOS",
    networksTitle: "REDES",
    bosqueMainDesc: "Bosque Gracias es un territorio artístico familiar ubicado en la zona rural da la Patagonia argentina, entre El Hoyo e Epuyén. Durante doce años, una familia de artistas ha vivido y construido este espacio, trabajando principalmente en audiovisuales y prácticas vinculadas a la Web3. El territorio promueve residencias que conectan naturaleza, tecnología y creación colectiva.\n\nEn enero de 2025, Kaêu y Qab participaron en la residencia como artistas residentes. Al año siguiente regresaron por invitación del equipo, integrándose al núcleo de documentación fotográfica e audiovisual.",
    dia1Title: "Día 1",
    dia1Text: "El primer día estuvo dedicado al reconocimiento del territorio y su historia.",
    dia2Title: "Día 2",
    tallerTitle: "Taller de Cianotipia",
    dia2Text: "En el segundo día se realizó el taller de cianotipia, dirigido por Rocío.",
    artesTitle: "ARTES",
    kaeuBio: "Kaêu Esuna es un multiartista quilombola cuya prática abarca performance, audiovisual, dirección creativa y educación artística.",
    qabBio: "Artista transdisciplinário de São Paulo, Qab Lima trabalha nas interseções entre arte digital, escultura, pintura, animación 2D, modelagem 3D, edición de video y producción musical. Sua prática investiga identidade, género y cuestiones sociopolíticas.",
    bosqueShortDesc: "Bosque Gracias es un territorio artístico familiar en la Patagonia Argentina que une naturaleza, tecnología y creación colectiva.",
    nostalgiaShortDesc: "Esta colección transforma memorias en futuro, recreando estéticas digitales da la infancia.",
    nostalgiaFullDesc: "Esta colección nació del deseo de transformar nuestros recuerdos en futuro. Se inspira en las referencias visuales que marcaron nuestra infancia y adolescencia – el arte digital temprano, brillos, collages, píxeles, universos online – y los recrea a través de quienes somos hoy.",
    watchHere: "MIRA AQUÍ",
    checkHere: "MIRA AQUÍ",
    clownmorfiaDesc: "Clownmorfia es un cortometraje de terror dirigido por Kaêu. La obra articula estética de moda y lenguaje del horror para tensionar el conservadurismo y la expresión de género.",
    uvs2Desc: "La colección revisita referencias adolescentes para expresar cómo se ve o mundo hoy, uniendo registro histórico y contemplación ancestral.",
    daguasDesc: "Película experimental rodada en Super 8 que sigue a una figura ancestral por São Paulo, evocando memorias borradas por el concreto.",
    brDesc: "Durante la residencia artística Bosque Gracias Summer 26' en la Patagonia, Argentina, Qab desarrolló una colección basada en 30 piedras recolectadas en el río. En cada una, Qab dibujó rostros y expresiones, permitiendo que los ángulos, formas y texturas naturales de las piedras guiaran el surgimiento de cada personaje.",
    bhhDesc: "Durante la residencia artística de Kismet Casa en Buenos Aires - Argentina, 2025, Qab desarrolló una colección inspirada en las cabezas de las personas participantes en esta residencia.",
    pinturasDesc: "Diferentes pinturas desarrolladas sobre lienzos y telas pintadas con gouache, óleo, tiza e outros materiais. Estas obras reflejan una intimidad de los sentimientos de Qab."
  }
};

export const GALLERY: ArtPiece[] = [
  { 
    id: '1', 
    title: 'Bosque Gracias Summer 2026', 
    imageUrl: 'https://lavender-worrying-clam-733.mypinata.cloud/ipfs/bafybeie5dbiugaytr5jvc45yhnmaeso36tr4oado7rdzvxtq4vshox4pwy', 
    description: 'Bosque Gracias é um território artístico familiar na Patagônia Argentina que une natureza, tecnologia e criação coletiva. Após incêndios devastadores em 2026, o projeto d...'
  },
  { 
    id: '2', 
    title: 'Nostalgia Utópica', 
    imageUrl: 'https://lavender-worrying-clam-733.mypinata.cloud/ipfs/bafybeihgzpmuyaxrolt37rvsv6usqcovfrqgqpcylswqghd7rfbxuisdve', 
    description: 'Esta coleção transforma memórias em futuro, recriando estéticas digitais da infância — pixels, colagens, brilhos e universos online — a partir de uma perspectiva trans e...'
  }
];
